version: '3'

services:
    swoft:
       image: swoft/swoft:latest
       container_name: swoft
       ports:
         - "666:80"
       volumes:
         - ./:/var/www/swoft
       stdin_open: true 
       tty: true
       privileged: true
       entrypoint: ["php", "/var/www/swoft/bin/swoft", "start"]
